# Generated by Django 5.2.1 on 2025-05-23 18:47

import django.core.validators
import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_facture', models.CharField(default=payments.models.generate_invoice_reference, max_length=100, unique=True, verbose_name='Référence unique')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant HT (€)')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Taux TVA (%)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant TTC (€)')),
                ('commission_taux', models.DecimalField(decimal_places=2, default=5.0, help_text='Commission de FreelanceHub', max_digits=5, verbose_name='Taux de commission (%)')),
                ('commission_montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant de commission (€)')),
                ('montant_freelance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant pour le freelance (€)')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Détails')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_recues', to=settings.AUTH_USER_MODEL, verbose_name='Client facturé')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_emises', to=settings.AUTH_USER_MODEL, verbose_name='Freelance émetteur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='missions.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_bloque', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant bloqué (€)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_liberation', models.DateTimeField(blank=True, null=True, verbose_name='Date de libération')),
                ('est_libere', models.BooleanField(default=False, verbose_name='Fonds libérés')),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_account', to='payments.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Compte Séquestre',
                'verbose_name_plural': 'Comptes Séquestre',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_paiement', models.CharField(default=payments.models.generate_payment_reference, max_length=100, unique=True, verbose_name='Référence paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé (€)')),
                ('methode_paiement', models.CharField(choices=[('STRIPE', 'Carte bancaire (Stripe)'), ('PAYPAL', 'PayPal'), ('BANK_TRANSFER', 'Virement bancaire'), ('ESCROW', 'Séquestre FreelanceHub')], max_length=50, verbose_name='Méthode de paiement')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé'), ('PROCESSING', 'En cours de traitement')], default='PENDING', max_length=20, verbose_name='Statut du paiement')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure du paiement')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.facture', verbose_name='Facture concernée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
