# Generated by Django 5.2 on 2025-05-03 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_facture', models.CharField(max_length=100, unique=True, verbose_name='Référence unique')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT (€)')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC (€)')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulée')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Détails')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_recues', to=settings.AUTH_USER_MODEL, verbose_name='Client facturé')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_emises', to=settings.AUTH_USER_MODEL, verbose_name='Freelance émetteur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='missions.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (€)')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure du paiement')),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode de paiement')),
                ('reference_transaction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence transaction externe')),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut du paiement')),
                ('details_passerelle', models.JSONField(blank=True, null=True, verbose_name='Détails Passerelle (JSON)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='payments.facture', verbose_name='Facture concernée')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
