# Generated by Django 5.2 on 2025-05-03 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'entreprise")),
                ('description_entreprise', models.TextField(blank=True, null=True, verbose_name="Description de l'entreprise")),
                ('site_web_entreprise', models.URLField(blank=True, null=True, verbose_name='Site Web')),
                ('adresse_entreprise', models.TextField(blank=True, null=True, verbose_name="Adresse de l'entreprise")),
                ('telephone_entreprise', models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de l'entreprise")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Client',
            },
        ),
        migrations.CreateModel(
            name='FreelanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_professionnel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre Professionnel')),
                ('competences', models.TextField(blank=True, null=True, verbose_name='Compétences')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Expérience')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Lien Portfolio')),
                ('taux_journalier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Taux Journalier Moyen (€)')),
                ('disponibilite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disponibilité')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Freelance',
                'verbose_name_plural': 'Profils Freelance',
            },
        ),
    ]
