# Generated by Django 5.2 on 2025-05-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre de la mission')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('competences_requises', models.TextField(blank=True, null=True, verbose_name='Compétences requises')),
                ('budget_propose', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget proposé (€)')),
                ('duree_estimee', models.CharField(blank=True, max_length=100, null=True, verbose_name='Durée estimée')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_limite_candidature', models.DateField(blank=True, null=True, verbose_name='Date limite pour postuler')),
                ('date_debut_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date de début souhaitée')),
                ('date_fin_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date de fin souhaitée')),
                ('statut', models.CharField(choices=[('OPEN', 'Ouverte'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20, verbose_name='Statut')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_publiees', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('freelance_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Freelance Assigné')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Message / Lettre de motivation')),
                ('proposition_tarifaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proposition tarifaire (€)')),
                ('date_candidature', models.DateTimeField(auto_now_add=True, verbose_name='Date de candidature')),
                ('statut', models.CharField(choices=[('SUBMITTED', 'Envoyée'), ('VIEWED', 'Vue'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée'), ('WITHDRAWN', 'Retirée')], default='SUBMITTED', max_length=20, verbose_name='Statut')),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_candidatures', to=settings.AUTH_USER_MODEL, verbose_name='Freelance Candidat')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='missions.mission', verbose_name='Mission Concernée')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
                'unique_together': {('mission', 'freelance')},
            },
        ),
    ]
