# Generated by Django 5.2.1 on 2025-05-23 18:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('est_prive', models.BooleanField(default=False, help_text="Visible uniquement par l'auteur", verbose_name='Commentaire privé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Commentaire de mission',
                'verbose_name_plural': 'Commentaires de mission',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MissionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du jalon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_completion', models.DateField(blank=True, null=True, verbose_name='Date de completion')),
                ('est_complete', models.BooleanField(default=False, verbose_name='Est complété')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Jalon de mission',
                'verbose_name_plural': 'Jalons de mission',
                'ordering': ['ordre', 'date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='MissionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_completion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de completion (%)')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('description_avancement', models.TextField(blank=True, null=True, verbose_name="Description de l'avancement")),
                ('mise_a_jour_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Progression de mission',
                'verbose_name_plural': 'Progressions de mission',
            },
        ),
        migrations.CreateModel(
            name='MissionStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(choices=[('OPEN', 'Ouverte'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée'), ('CANCELLED', 'Annulée')], max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('OPEN', 'Ouverte'), ('ASSIGNED', 'Assignée'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CLOSED', 'Fermée'), ('CANCELLED', 'Annulée')], max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur de la modification')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='missions.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Mise à jour de statut',
                'verbose_name_plural': 'Mises à jour de statut',
                'ordering': ['-date_modification'],
            },
        ),
    ]
